services:
  # Service untuk Redis (Antrean BullMQ)
  redis:
    image: redis:7-alpine
    container_name: spe_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass password_rahasia_kamu
    volumes:
      - redis_data:/data
    restart: 'no'

  # Service untuk MongoDB (Database Utama & Timeline)
  mongodb:
    image: mongo:latest
    container_name: spe_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: 'no'

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/data
    restart: 'no'

volumes:
  redis_data:
  mongo_data:
  ollama_data:
